---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rust-api
  name: rust-api-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: rust-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
        - name: rust-api
          image: rust-api:latest
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          ports:
            - containerPort: 9000
              name: api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rust-api-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - periodSeconds: 60
          type: Pods
          value: 3
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - periodSeconds: 120
          type: Pods
          value: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
---
apiVersion: v1
kind: Service
metadata:
  name: rust-api
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 9000
  selector:
    app: rust-api
