---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api-deployment
spec:
  template:
    spec:
      containers:
        - name: rust-api
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
