apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: configmaps/deployments-conf.yaml
  - path: deployments/api/base.yaml
  - path: deployments/api/extras-deployment.yaml
  # - path: deployments/db/base.yaml
